module.exports = {
  AE: 'United Arab Emirates',
  AG: 'Antigua and Barbuda',
  AL: 'Albania (EP)',
  AM: 'Armenia (EA)',
  AO: 'Angola',
  AT: 'Austria (EP)',
  AU: 'Australia',
  AZ: 'Azerbaijan (EA)',
  HK: "Honk Kong",
  BA: 'Bosnia and Herzegovina',
  BB: 'Barbados',
  BE: 'Belgium (EP)',
  BF: 'Burkina Faso (OA)',
  BG: 'Bulgaria (EP)',
  BH: 'Bahrain',
  BJ: 'Benin (OA)',
  BN: 'Brunei Darussalam',
  BR: 'Brazil',
  BW: 'Botswana (AP)',
  BY: 'Belarus (EA)',
  TW: "Taiwan",
  TWM: "Taiwan",
  TWI: "Taiwan",
  BZ: 'Belize',
  CA: 'Canada',
  CF: 'Central African Republic (OA)',
  CG: 'Congo (OA)',
  CH: 'Switzerland (EP)',
  CI: 'Côte d’Ivoire (OA)',
  CL: 'Chile',
  CM: 'Cameroon (OA)',
  CN: 'China',
  CO: 'Colombia',
  CR: 'Costa Rica',
  CU: 'Cuba',
  CV: 'Cabo Verde (AP)',

  CY: 'Cyprus (EP)',
  CZ: 'Czechia (EP)',
  DE: 'Germany (EP)',
  DJ: 'Djibouti',
  DK: 'Denmark (EP)',
  DM: 'Dominica',
  DO: 'Dominican Republic',
  DZ: 'Algeria',
  EC: 'Ecuador',
  EE: 'Estonia (EP)',
  EG: 'Egypt',
  ES: 'Spain (EP)',
  FI: 'Finland (EP)',
  FR: 'France (EP)',
  GA: 'Gabon (OA)',
  GB: 'United Kingdom (EP)',
  GD: 'Grenada',
  GE: 'Georgia',
  GH: 'Ghana (AP)',
  GM: 'Gambia (AP)',
  GN: 'Guinea (OA)',
  GQ: 'Equatorial Guinea (OA)',
  GR: 'Greece (EP)',
  GT: 'Guatemala',
  GW: 'Guinea-Bissau (OA)',
  HN: 'Honduras',
  HR: 'Croatia (EP)',
  HU: 'Hungary (EP)',
  ID: 'Indonesia',
  IE: 'Ireland (EP)',
  IL: 'Israel',
  IN: 'India',
  IQ: 'Iraq',

  IR: 'Iran (Islamic Republic of)',
  IS: 'Iceland (EP)',
  IT: 'Italy (EP)',
  JM: 'Jamaica',
  JO: 'Jordan',
  JP: 'Japan',
  JPH: 'Japan',
  KE: 'Kenya (AP)',
  KG: 'Kyrgyzstan (EA)',
  KH: 'Cambodia',
  KM: 'Comoros (OA)',
  KN: 'Saint Kitts and Nevis',
  KP: 'Democratic People’s Republic of Korea',
  KR: 'Republic of Korea',
  KW: 'Kuwait',
  KZ: 'Kazakhstan (EA)',
  LA: 'Lao People’s Democratic Republic',
  LC: 'Saint Lucia',
  LI: 'Liechtenstein (EP)',
  LK: 'Sri Lanka',
  LR: 'Liberia (AP)',
  LS: 'Lesotho (AP)',
  LT: 'Lithuania (EP)',
  LU: 'Luxembourg (EP)',
  LV: 'Latvia (EP)',
  LY: 'Libya',
  MA: 'Morocco',
  MC: 'Monaco (EP)',
  MD: 'Republic of Moldova',
  ME: 'Montenegro (EP)',
  MG: 'Madagascar',
  MK: 'North Macedonia (EP)',

  ML: 'Mali (OA)',
  MN: 'Mongolia',
  MR: 'Mauritania (OA)',
  MT: 'Malta (EP)',
  MU: 'Mauritius',
  MW: 'Malawi (AP)',
  MX: 'Mexico',
  MXPA: 'Mexico',
  MY: 'Malaysia',
  MZ: 'Mozambique (AP)',
  NA: 'Namibia (AP)',
  NE: 'Niger (OA)',
  NG: 'Nigeria',
  NI: 'Nicaragua',
  NL: 'Netherlands (EP)',
  NO: 'Norway (EP)',
  NZ: 'New Zealand',
  OM: 'Oman',
  PA: 'Panama',
  PE: 'Peru',
  PG: 'Papua New Guinea',
  PH: 'Philippines',
  PL: 'Poland (EP)',
  PT: 'Portugal (EP)',
  QA: 'Qatar',
  RO: 'Romania (EP)',
  RS: 'Serbia (EP)',
  RU: 'Russian Federation (EA)',
  RW: 'Rwanda (AP)',
  SA: 'Saudi Arabia',
  SC: 'Seychelles (AP)',
  SD: 'Sudan (AP)',
  SE: 'Sweden (EP)',
  SG: 'Singapore',

  SI: 'Slovenia (EP)',
  SK: 'Slovakia (EP)',
  SL: 'Sierra Leone (AP)',
  SM: 'San Marino (EP)',
  SN: 'Senegal (OA)',
  ST: 'Sao Tome and Principe (AP)',
  SV: 'El Salvador',
  SY: 'Syrian Arab Republic',
  SZ: 'Eswatini (AP)',
  TD: 'Chad (OA)',
  TG: 'Togo (OA)',
  TH: 'Thailand',
  TJ: 'Tajikistan (EA)',
  TM: 'Turkmenistan (EA)',
  TN: 'Tunisia',
  TR: 'Türkiye (EP)',
  TT: 'Trinidad and Tobago',
  TZ: 'United Republic of Tanzania (AP)',
  UA: 'Ukraine',
  UG: 'Uganda (AP)',
  US: 'United States of America',
  UY: 'Uruguay',
  UZ: 'Uzbekistan',
  VC: 'Saint Vincent and the Grenadines',
  VN: 'Viet Nam',
  WS: 'Samoa',
  ZA: 'South Africa',
  ZM: 'Zambia (AP)',
  ZW: 'Zimbabwe (AP)',

   // Major Patent Organizations
   WO: 'World Intellectual Property Organization (WIPO / PCT)',
   EP: 'European Patent Office (EPO)',
   EA: 'Eurasian Patent Organization (EAPO)',
   OA: 'African Intellectual Property Organization (OAPI)',
   AP: 'African Regional Intellectual Property Organization (ARIPO)',
   GC: 'Gulf Cooperation Council Patent Office (GCCPO)',
 
   // Historical / Special Codes
   YU: 'Yugoslavia (Historical)',
  SU: 'Soviet Union (Historical)',
  DD: 'East Germany (Historical)',
  IB: 'International Bureau (WIPO context)',
  EM: 'European Union IP Office (Designs/Trademarks)',

  // Misc / Placeholder
  X: 'Placeholder / Unknown authority',
  XX: 'Placeholder / Unknown authority',

  // Patent Country Codes (3-Letter)
  ALB: 'Albania',
  AND: 'Andorra',
  ARM: 'Armenia',
  DZA: 'Algeria',
  AGO: 'Angola',
  ARG: 'Argentina',
  AUS: 'Australia',
  AUT: 'Austria',
  AZE: 'Azerbaijan',
  BHS: 'Bahamas',
  BHR: 'Bahrain',
  BGD: 'Bangladesh',
  BRB: 'Barbados',
  BLR: 'Belarus',
  BEL: 'Belgium',
  BLZ: 'Belize',
  BEN: 'Benin',
  BOL: 'Bolivia',
  BIH: 'Bosnia and Herzegovina',
  BWA: 'Botswana',
  BRA: 'Brazil',
  BRN: 'Brunei Darussalam',
  BGR: 'Bulgaria',
  BFA: 'Burkina Faso',
  BDI: 'Burundi',
  CPV: 'Cabo Verde',
  KHM: 'Cambodia',
  CMR: 'Cameroon',
  CUB: 'Cuba',
  CZE: 'Czechia',
  DNK: 'Denmark',
  DJI: 'Djibouti',
  DMA: 'Dominica',
  DOM: 'Dominican Republic',
  ECU: 'Ecuador',
  EGY: 'Egypt',
  SLV: 'El Salvador',
  GNQ: 'Equatorial Guinea',
  ERI: 'Eritrea',
  EST: 'Estonia',
  ETH: 'Ethiopia',
  FJI: 'Fiji',
  FIN: 'Finland',
  FRA: 'France',
  GAB: 'Gabon',
  GMB: 'Gambia',
  GEO: 'Georgia',
  DEU: 'Germany',
  GHA: 'Ghana',
  GRC: 'Greece',
  GRD: 'Grenada',
  GUM: 'Guam',
  GTM: 'Guatemala',
  GIN: 'Guinea',
  GNB: 'Guinea-Bissau',
  GUY: 'Guyana',
  HTI: 'Haiti',
  HND: 'Honduras',
  HUN: 'Hungary (EP)',
  ISL: 'Iceland',
  IND: 'India',
  IDN: 'Indonesia',
  IRN: 'Iran',
  IRQ: 'Iraq',
  IRL: 'Ireland',
  ISR: 'Israel',
  ITA: 'Italy',
  JAM: 'Jamaica',
  JPN: 'Japan',
  JOR: 'Jordan',
  KAZ: 'Kazakhstan',
  KEN: 'Kenya',
  KIR: 'Kiribati',
  KOR: 'Korea (Republic of)',
  KWT: 'Kuwait',
  KGZ: 'Kyrgyzstan',
  LAO: 'Laos',
  LVA: 'Latvia',
  LBN: 'Lebanon',
  LSO: 'Lesotho',
  LBR: 'Liberia',
  LIE: 'Liechtenstein',
  LTU: 'Lithuania',
  LUX: 'Luxembourg',
  MAC: 'Macau',
  MDG: 'Madagascar',
  MWI: 'Malawi',
  MYS: 'Malaysia',
  MDV: 'Maldives',
  MLI: 'Mali',
  MLT: 'Malta',
  MHL: 'Marshall Islands',
  MEX: 'Mexico',
  FSM: 'Micronesia (Federated States)',
  MDA: 'Moldova',
  MCO: 'Monaco',
  MNG: 'Mongolia',
  MNE: 'Montenegro',
  MOZ: 'Mozambique',
  MMR: 'Myanmar',
  NAM: 'Namibia',
  NRU: 'Nauru',
  NPL: 'Nepal',
  NLD: 'Netherlands',
  NZL: 'New Zealand',
  NIC: 'Nicaragua',
  NER: 'Niger',
  NGA: 'Nigeria',
  PRK: 'North Korea',
  MKD: 'North Macedonia',
  NOR: 'Norway',
  OMN: 'Oman',
  PAK: 'Pakistan',
  PLW: 'Palau',
  PSE: 'Palestinian Territory',
  PAN: 'Panama',
  PNG: 'Papua New Guinea',
  PRY: 'Paraguay',
  PER: 'Peru',
  PHL: 'Philippines',
  POL: 'Poland',
  PRT: 'Portugal',
  QAT: 'Qatar',
  ROU: 'Romania',
  RUS: 'Russia',
  RWA: 'Rwanda',
  KNA: 'Saint Kitts and Nevis',
  LCA: 'Saint Lucia',
  VCT: 'Saint Vincent and the Grenadines',
  SAU: 'Saudi Arabia',
  SEN: 'Senegal',
  SRB: 'Serbia',
  SYR: 'Syria',
  SLE: 'Sierra Leone',
  SING: 'Singapore',
  SLO: 'Slovenia',
  SLK: 'Slovakia',
  SUD: 'Sudan',
  SUR: 'Suriname',
  SWE: 'Sweden',
  SWZ: 'Swaziland',
  SYC: 'Seychelles',
  TGO: 'Togo',
  TON: 'Tonga',
  TTO: 'Trinidad and Tobago',
  TUN: 'Tunisia',
  TUR: 'Turkey',
  TUV: 'Tuvalu',
  TZA: 'Tanzania',
  UGA: 'Uganda',
  UKR: 'Ukraine',
  ARE: 'United Arab Emirates',
  GBR: 'United Kingdom',
  URY: 'Uruguay',
  USA: 'United States',
  USRE: 'United States',
  VUT: 'Vanuatu',
  VEN: 'Venezuela',
  VNM: 'Vietnam',
  WSM: 'Samoa',
  YEM: 'Yemen',
  ZMB: 'Zambia',
  ZWE: 'Zimbabwe',
  HUE: 'Hungary (EP)'

  

  
};
